### ISSUE TITLE
Permision denied to the mapped folder

### ISSUE THREAD

**Issue by dburner** [Ostico/docker_matecat#4]
Hello, when I use these images all http requests come empty but the php header is pressent. Reading from `/var/log/apache2/matecat/error.log` in the matecat container I can see this error message:

```
PHP Stack trace:
PHP   1. Bootstrap::fatalErrorHandler() /var/www/matecat/inc/Bootstrap.php:0
PHP   2. Log::doLog() /var/www/matecat/inc/Bootstrap.php:200
PHP   3. Log::_writeTo() /var/www/matecat/lib/Utils/Log.php:122
PHP   4. file_put_contents() /var/www/matecat/lib/Utils/Log.php:57
PHP Warning:  file_put_contents(/var/www/matecat/local_storage/log_archive/fatal_errors.txt): failed to open stream: Permission denied in /var/www/matecat/lib/Utils/Log.php on line 57

```

Do you have any ideea on how can I resolve this problem?

Thanks

**Comment by Ostico** [comment]
The Readme is not up to date, please can you explain better what you done? 
This repository is not meant to be used in production as is, but only to try the software and for development.

**Comment by dburner** [comment]
Well I did what the readme said, but here are all the steps:
- fresh install ubuntu server 16
- installed latest docker and docker-compose
- had this issue https://github.com/docker/compose/issues/1214 (dont remember how i solved it)
- clone the matecat repto into ~/matecat
- cloned this repo
- copied the docker-compose.yml into the repo root folder from MateCat-Trusty and removed all of the enviroment variables from matecat (except from matecatfilters) also changed the volume mount to ` - ~/matecat:/var/www/matecat:rw`

Note: the apache server actually responds to requests if i make a request to a static file (for ex an image) from the matecat folder. I think I just can't write to it.

Thanks for the quit response

**Comment by Ostico** [comment]
I assume you configured MateCat correctly.

Seems the server has some kind of permission issues, i suggest you to enter inside the docker container and run `killall php` a `chown -R /var/www/matecat`, after that go in the daemons directory and run the bash script `/var/www/matecat/daemons/restartAnalysis.sh`

**Comment by dburner** [comment]
That did solve the problem, thanks but now I get an `Ops an error has occurred` when I press analyze to analyze a regex, the error.log of apache does not show any errors tho.

**Comment by Ostico** [comment]
Check the log `/var/www/matecat/local_storage/fatal_errors.log` to get more info.

Anyway, the master branch are fresh updated now, it should work from scratch if you recreate the images and the containers.

**Comment by Ostico** [comment]
Delete the files `config.ini` and `task_manager_config.ini` inside MateCat and re-create all the images.

**Comment by dburner** [comment]
Thanks, it worked.
I still had to run `chown -R ${USER_OWNER} /var/www/matecat` in the matecat container for it to work, but it may be only a problem in my VM.
