### ISSUE TITLE
cannot analyze

### ISSUE THREAD

**Issue by philippehenri** [Ostico/docker_matecat#6]
Hi
I ran this docker, and when i am willing to click on Analyse after having uploaded a file, nothing happen?

Any idea of what i could check?
thanks
Phil

**Comment by Ostico** [comment]
Can you provide more info?

**Comment by philippehenri** [comment]
Dear Domenico, thanks for your answer, Since i couldn't make it work,  i now use a local matecat with the virtualbox image for testing.
