### ISSUE TITLE
errors during docker-compose up

### ISSUE THREAD

**Issue by stevennt** [Ostico/docker_matecat#9]
I have the following errors during docker-compose up
Any suggestion? Thanks.

docker_mysql | 2019-09-28T18:19:04.015428Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
docker_mysql | 2019-09-28T18:19:04.015501Z 0 [ERROR] Aborting
docker_mysql | 

docker_amq | INFO: Loading '/opt/apache-activemq-5.13.2//bin/env'
docker_matecat_filter | 2019-09-28 18:19:05:854 [main] WARN Config - cache-folder param empty or invalid: caching in OS temp folder
redis_1    | 1:M 28 Sep 2019 18:19:04.555 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1    | 1:M 28 Sep 2019 18:19:04.555 # Server initialized
redis_1    | 1:M 28 Sep 2019 18:19:04.555 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
docker_mysql | Executing: mysqld_safe --defaults-file=/etc/mysql/my.cnf --user=mysql --plugin-dir=/usr/lib/mysql/plugin
docker_mysql | => Waiting for confirmation of MySQL service startup
docker_amq | INFO: Using java '/usr/bin/java'
redis_1    | 1:M 28 Sep 2019 18:19:04.555 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1    | 1:M 28 Sep 2019 18:19:04.555 * DB loaded from disk: 0.000 seconds
redis_1    | 1:M 28 Sep 2019 18:19:04.555 * Ready to accept connections
docker_mysql | 2019-09-28T18:19:04.229843Z mysqld_safe Logging to '/var/log/mysql/error.log'.
docker_matecat_filter | 2019-09-28 18:19:05:855 [main] WARN Config - error-folder param empty or invalid: errors backup disabled
docker_amq | Java Runtime: Private Build 1.8.0_222 /usr/lib/jvm/java-8-openjdk-amd64/jre
docker_matecat | => Waiting for confirmation of MySQL service startup
docker_amq |   Heap sizes: current=62976k  free=62320k  max=932352k
docker_matecat_filter | 2019-09-28 18:19:05:856 [main] WARN Config - custom-segmentation-folder param empty or invalid: custom segmentation disabled
docker_mysql | 2019-09-28T18:19:04.241184Z mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
docker_mysql | 2019-09-28T18:19:07.192055Z mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended
docker_amq |     JVM args: -Xms64M -Xmx1G -Djava.util.logging.config.file=logging.properties -Djava.security.auth.login.config=/opt/apache-activemq-5.13.2//conf/login.config -Dactivemq.classpath=/opt/apache-activemq-5.13.2//conf:/opt/apache-activemq-5.13.2//../lib/: -Dactivemq.home=/opt/apache-activemq-5.13.2/ -Dactivemq.base=/opt/apache-activemq-5.13.2/ -Dactivemq.conf=/opt/apache-activemq-5.13.2//conf -Dactivemq.data=/opt/apache-activemq-5.13.2//data

**Comment by Ostico** [comment]
Mysql says that the data directory is not empty.
Destroy mysql service image and try to build it again.

Il sab 28 set 2019, 20:22 www.AbnAsia.org <notifications@github.com> ha
scritto:
